//This file is generated by GNU make, do not edit.
//This generated file is used in ../Plug.h .
PluginTX_id[x]=1;PluginTX_ptr[x++]=&PluginTX_003;
PluginTX_id[x]=2;PluginTX_ptr[x++]=&PluginTX_004;
PluginTX_id[x]=3;PluginTX_ptr[x++]=&PluginTX_005;
PluginTX_id[x]=4;PluginTX_ptr[x++]=&PluginTX_006;
PluginTX_id[x]=5;PluginTX_ptr[x++]=&PluginTX_007;
PluginTX_id[x]=6;PluginTX_ptr[x++]=&PluginTX_008;
PluginTX_id[x]=7;PluginTX_ptr[x++]=&PluginTX_009;
PluginTX_id[x]=8;PluginTX_ptr[x++]=&PluginTX_010;
PluginTX_id[x]=9;PluginTX_ptr[x++]=&PluginTX_011;
PluginTX_id[x]=10;PluginTX_ptr[x++]=&PluginTX_012;
PluginTX_id[x]=11;PluginTX_ptr[x++]=&PluginTX_013;
PluginTX_id[x]=12;PluginTX_ptr[x++]=&PluginTX_015;
PluginTX_id[x]=13;PluginTX_ptr[x++]=&PluginTX_070;
PluginTX_id[x]=14;PluginTX_ptr[x++]=&PluginTX_072;
PluginTX_id[x]=15;PluginTX_ptr[x++]=&PluginTX_073;
PluginTX_id[x]=16;PluginTX_ptr[x++]=&PluginTX_074;
PluginTX_id[x]=17;PluginTX_ptr[x++]=&PluginTX_080;
PluginTX_id[x]=18;PluginTX_ptr[x++]=&PluginTX_082;
