//This file is generated by GNU make, do not edit.
#ifndef _plugin_043_h
	#define _plugin_043_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_043
		#include "../Base.h"
		//prototype functions
		boolean Plugin_043(byte function, char *string);
	#endif
#endif
