//This file is generated by GNU make, do not edit.
#ifndef _plugin_063_h
	#define _plugin_063_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_063
		#include "../Base.h"
		//prototype functions
		boolean Plugin_063(byte function, char *string);
	#endif
#endif
