//This file is generated by GNU make, do not edit.
#ifndef _plugin_048_h
	#define _plugin_048_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_048
		#include "../Base.h"
		//prototype functions
		boolean Plugin_048(byte function, char *string);
	#endif
#endif
