//This file is generated by GNU make, do not edit.
#ifndef _plugin_013_h
	#define _plugin_013_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_013
		#include "../Base.h"
		//prototype functions
		boolean Plugin_013(byte function, char *string);
		boolean PluginTX_013(byte function, char *string);
	#endif
#endif
