//This file is generated by GNU make, do not edit.
#ifndef _plugin_044_h
	#define _plugin_044_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_044
		#include "../Base.h"
		//prototype functions
		boolean Plugin_044(byte function, char *string);
	#endif
#endif
