//This file is generated by GNU make, do not edit.
#ifndef _plugin_045_h
	#define _plugin_045_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_045
		#include "../Base.h"
		//prototype functions
		boolean Plugin_045(byte function, char *string);
	#endif
#endif
