//This file is generated by GNU make, do not edit.
#ifndef _plugin_032_h
	#define _plugin_032_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_032
		#include "../Base.h"
		//prototype functions
		boolean Plugin_032(byte function, char *string);
	#endif
#endif
