//This file is generated by GNU make, do not edit.
#ifndef _plugin_041_h
	#define _plugin_041_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_041
		#include "../Base.h"
		//prototype functions
		boolean Plugin_041(byte function, char *string);
	#endif
#endif
