//This file is generated by GNU make, do not edit.
#ifndef _plugin_042_h
	#define _plugin_042_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_042
		#include "../Base.h"
		//prototype functions
		boolean Plugin_042(byte function, char *string);
	#endif
#endif
