//This file is generated by GNU make, do not edit.
#ifndef _plugin_033_h
	#define _plugin_033_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_033
		#include "../Base.h"
		//prototype functions
		boolean Plugin_033(byte function, char *string);
	#endif
#endif
