//This file is generated by GNU make, do not edit.
#ifndef _plugin_080_h
	#define _plugin_080_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_080
		#include "../Base.h"
		//prototype functions
		boolean Plugin_080(byte function, char *string);
		boolean PluginTX_080(byte function, char *string);
	#endif
#endif
