//This file is generated by GNU make, do not edit.
#ifndef _plugin_100_h
	#define _plugin_100_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_100
		#include "../Base.h"
		//prototype functions
		boolean Plugin_100(byte function, char *string);
	#endif
#endif
