//This file is generated by GNU make, do not edit.
#ifndef _plugin_031_h
	#define _plugin_031_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_031
		#include "../Base.h"
		//prototype functions
		boolean Plugin_031(byte function, char *string);
	#endif
#endif
