//This file is generated by GNU make, do not edit.
#ifndef _plugin_011_h
	#define _plugin_011_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_011
		#include "../Base.h"
		//prototype functions
		boolean Plugin_011(byte function, char *string);
		boolean PluginTX_011(byte function, char *string);
	#endif
#endif
