//This file is generated by GNU make, do not edit.
#ifndef _plugin_046_h
	#define _plugin_046_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_046
		#include "../Base.h"
		//prototype functions
		boolean Plugin_046(byte function, char *string);
	#endif
#endif
