//This file is generated by GNU make, do not edit.
#ifndef _plugin_010_h
	#define _plugin_010_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_010
		#include "../Base.h"
		//prototype functions
		boolean Plugin_010(byte function, char *string);
		boolean PluginTX_010(byte function, char *string);
	#endif
#endif
