//This file is generated by GNU make, do not edit.
#ifndef _plugin_007_h
	#define _plugin_007_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_007
		#include "../Base.h"
		//prototype functions
		boolean Plugin_007(byte function, char *string);
		boolean PluginTX_007(byte function, char *string);
	#endif
#endif
