//This file is generated by GNU make, do not edit.
#ifndef _plugin_008_h
	#define _plugin_008_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_008
		#include "../Base.h"
		//prototype functions
		boolean Plugin_008(byte function, char *string);
		boolean PluginTX_008(byte function, char *string);
	#endif
#endif
