//This file is generated by GNU make, do not edit.
#ifndef _plugin_061_h
	#define _plugin_061_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_061
		#include "../Base.h"
		//prototype functions
		boolean Plugin_061(byte function, char *string);
	#endif
#endif
