//This file is generated by GNU make, do not edit.
#ifndef _plugin_082_h
	#define _plugin_082_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_082
		#include "../Base.h"
		//prototype functions
		boolean Plugin_082(byte function, char *string);
		boolean PluginTX_082(byte function, char *string);
	#endif
#endif
