//This file is generated by GNU make, do not edit.
#ifndef _plugin_073_h
	#define _plugin_073_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_073
		#include "../Base.h"
		//prototype functions
		boolean Plugin_073(byte function, char *string);
		boolean PluginTX_073(byte function, char *string);
	#endif
#endif
