//This file is generated by GNU make, do not edit.
#ifndef _plugin_090_h
	#define _plugin_090_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_090
		#include "../Base.h"
		//prototype functions
		boolean Plugin_090(byte function, char *string);
	#endif
#endif
