//This file is generated by GNU make, do not edit.
#ifndef _plugin_071_h
	#define _plugin_071_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_071
		#include "../Base.h"
		//prototype functions
		boolean Plugin_071(byte function, char *string);
	#endif
#endif
