//This file is generated by GNU make, do not edit.
#ifndef _plugin_030_h
	#define _plugin_030_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_030
		#include "../Base.h"
		//prototype functions
		boolean Plugin_030(byte function, char *string);
	#endif
#endif
