//This file is generated by GNU make, do not edit.
#ifndef _plugin_012_h
	#define _plugin_012_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_012
		#include "../Base.h"
		//prototype functions
		boolean Plugin_012(byte function, char *string);
		boolean PluginTX_012(byte function, char *string);
	#endif
#endif
