//This file is generated by GNU make, do not edit.
#ifndef _plugin_034_h
	#define _plugin_034_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_034
		#include "../Base.h"
		//prototype functions
		boolean Plugin_034(byte function, char *string);
	#endif
#endif
