//This file is generated by GNU make, do not edit.
#ifndef _plugin_004_h
	#define _plugin_004_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_004
		#include "../Base.h"
		//prototype functions
		boolean Plugin_004(byte function, char *string);
		boolean PluginTX_004(byte function, char *string);
	#endif
#endif
