//This file is generated by GNU make, do not edit.
#ifndef _plugin_074_h
	#define _plugin_074_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_074
		#include "../Base.h"
		//prototype functions
		boolean Plugin_074(byte function, char *string);
		boolean PluginTX_074(byte function, char *string);
	#endif
#endif
