//This file is generated by GNU make, do not edit.
#ifndef _plugin_002_h
	#define _plugin_002_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_002
		#include "../Base.h"
		//prototype functions
		boolean Plugin_002(byte function, char *string);
	#endif
#endif
