//This file is generated by GNU make, do not edit.
#ifndef _plugin_005_h
	#define _plugin_005_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_005
		#include "../Base.h"
		//prototype functions
		boolean Plugin_005(byte function, char *string);
		boolean PluginTX_005(byte function, char *string);
	#endif
#endif
