//This file is generated by GNU make, do not edit.
#ifndef _plugin_014_h
	#define _plugin_014_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_014
		#include "../Base.h"
		//prototype functions
		boolean Plugin_014(byte function, char *string);
	#endif
#endif
