//This file is generated by GNU make, do not edit.
#ifndef _plugin_009_h
	#define _plugin_009_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_009
		#include "../Base.h"
		//prototype functions
		boolean Plugin_009(byte function, char *string);
		boolean PluginTX_009(byte function, char *string);
	#endif
#endif
