//This file is generated by GNU make, do not edit.
#ifndef _plugin_006_h
	#define _plugin_006_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_006
		#include "../Base.h"
		//prototype functions
		boolean Plugin_006(byte function, char *string);
		boolean PluginTX_006(byte function, char *string);
	#endif
#endif
