//This file is generated by GNU make, do not edit.
#ifndef _plugin_070_h
	#define _plugin_070_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_070
		#include "../Base.h"
		//prototype functions
		boolean Plugin_070(byte function, char *string);
		boolean PluginTX_070(byte function, char *string);
	#endif
#endif
