//This file is generated by GNU make, do not edit.
#ifndef _plugin_035_h
	#define _plugin_035_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_035
		#include "../Base.h"
		//prototype functions
		boolean Plugin_035(byte function, char *string);
	#endif
#endif
