//This file is generated by GNU make, do not edit.
#ifndef _plugin_072_h
	#define _plugin_072_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_072
		#include "../Base.h"
		//prototype functions
		boolean Plugin_072(byte function, char *string);
		boolean PluginTX_072(byte function, char *string);
	#endif
#endif
