//This file is generated by GNU make, do not edit.
#ifndef _plugin_254_h
	#define _plugin_254_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_254
		#include "../Base.h"
		//prototype functions
		boolean Plugin_254(byte function, char *string);
	#endif
#endif
