//This file is generated by GNU make, do not edit.
#ifndef _plugin_040_h
	#define _plugin_040_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_040
		#include "../Base.h"
		//prototype functions
		boolean Plugin_040(byte function, char *string);
	#endif
#endif
