//This file is generated by GNU make, do not edit.
#ifndef _plugin_015_h
	#define _plugin_015_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_015
		#include "../Base.h"
		//prototype functions
		boolean Plugin_015(byte function, char *string);
		boolean PluginTX_015(byte function, char *string);
	#endif
#endif
