//This file is generated by GNU make, do not edit.
#ifndef _plugin_062_h
	#define _plugin_062_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_062
		#include "../Base.h"
		//prototype functions
		boolean Plugin_062(byte function, char *string);
	#endif
#endif
