//This file is generated by GNU make, do not edit.
#ifndef _plugin_003_h
	#define _plugin_003_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_003
		#include "../Base.h"
		//prototype functions
		boolean Plugin_003(byte function, char *string);
		boolean PluginTX_003(byte function, char *string);
	#endif
#endif
