//This file is generated by GNU make, do not edit.
#ifndef _plugin_075_h
	#define _plugin_075_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_075
		#include "../Base.h"
		//prototype functions
		boolean Plugin_075(byte function, char *string);
	#endif
#endif
