//This file is generated by GNU make, do not edit.
#ifndef _plugin_060_h
	#define _plugin_060_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_060
		#include "../Base.h"
		//prototype functions
		boolean Plugin_060(byte function, char *string);
	#endif
#endif
