//This file is generated by GNU make, do not edit.
#ifndef _plugin_001_h
	#define _plugin_001_h
	#include "../../Config/Config_02.c"
	#ifdef PLUGIN_001
		#include "../Base.h"
		//prototype functions
		boolean Plugin_001(byte function, char *string);
	#endif
#endif
